sonar.projectName=learning-managment-system
sonar.sourceEncoding=UTF-8

# Java build metadata is provided by Maven scanner execution in CI.
sonar.sources=lms-common/src/main,lms-gateway/src/main,services
sonar.tests=lms-common/src/test,lms-gateway/src/test,services
sonar.java.binaries=**/target/classes
sonar.junit.reportPaths=**/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
