-- Enable extensions required by microservices
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE SCHEMA IF NOT EXISTS lms_user;
CREATE SCHEMA IF NOT EXISTS lms_course;
CREATE SCHEMA IF NOT EXISTS lms_enrollment;
CREATE SCHEMA IF NOT EXISTS lms_auth;
CREATE SCHEMA IF NOT EXISTS lms_content;
CREATE SCHEMA IF NOT EXISTS lms_assignment;
CREATE SCHEMA IF NOT EXISTS lms_payment;
CREATE SCHEMA IF NOT EXISTS lms_analytics;
