CREATE SCHEMA IF NOT EXISTS lms_user;
CREATE SCHEMA IF NOT EXISTS lms_course;
CREATE SCHEMA IF NOT EXISTS lms_enrollment;
CREATE SCHEMA IF NOT EXISTS lms_auth;
CREATE SCHEMA IF NOT EXISTS lms_content;
