{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lms-backend.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "lms-backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
{{- range $name, $value := .Values.secrets }}
  {{ $name }}: {{ $value | quote }}
{{- end }}
{{- end }}
