apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lms-backend-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Mukeshmehta2041/enterprise-learning-management-system.git
    targetRevision: main
    path: infra/helm/lms-backend
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: lms-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
